# Log Channel Configurations
# Maps event types to channel IDs. The destination channels are sourced from
# .env (see config.py LOG_CHANNEL_*_ID variables); the literals in config.py
# are fallback defaults.

from config import (
    LOG_CHANNEL_MEMBERS_ID,
    LOG_CHANNEL_ROLES_ID,
    LOG_CHANNEL_CHANNELS_ID,
    LOG_CHANNEL_TIMEOUTS_ID,
    LOG_CHANNEL_VOICE_ID,
    LOG_CHANNEL_WARNINGS_ID,
    LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    LOG_CHANNEL_MODERATION_ID,
    LOG_CHANNEL_TICKETS_ID,
    LOG_CHANNEL_STAFF_POINTS_ID,
)

LOG_CHANNEL_MAP = {
    # Join/Leave
    "MEMBER_JOIN": LOG_CHANNEL_MEMBERS_ID,
    "MEMBER_LEAVE": LOG_CHANNEL_MEMBERS_ID,
    "MEMBER_JOIN_BOT": LOG_CHANNEL_MEMBERS_ID,
    "MEMBER_LEAVE_BOT": LOG_CHANNEL_MEMBERS_ID,
    # Channel Updates (permissions / visibility / topic / name)
    "CHANNEL_UPDATE": LOG_CHANNEL_CHANNELS_ID,
    # Timeout
    "TIMEOUT_APPLIED": LOG_CHANNEL_TIMEOUTS_ID,
    "TIMEOUT_REMOVED": LOG_CHANNEL_TIMEOUTS_ID,
    "TIMEOUT_EXPIRED": LOG_CHANNEL_TIMEOUTS_ID,
    # VC Logs (mute/deafen by mod or moved by mod)
    "VOICE_MUTE": LOG_CHANNEL_VOICE_ID,
    "VOICE_UNMUTE": LOG_CHANNEL_VOICE_ID,
    "VOICE_DEAFEN": LOG_CHANNEL_VOICE_ID,
    "VOICE_UNDEAFEN": LOG_CHANNEL_VOICE_ID,
    "VOICE_DISCONNECT": LOG_CHANNEL_VOICE_ID,
    "VOICE_MOVE": LOG_CHANNEL_VOICE_ID,
    # Warning
    "WARN": LOG_CHANNEL_WARNINGS_ID,
    # Role Create/Delete
    "ROLE_CREATE": LOG_CHANNEL_ROLES_ID,
    "ROLE_DELETE": LOG_CHANNEL_ROLES_ID,
    # Channel Create/Delete
    "CHANNEL_DELETE": LOG_CHANNEL_CHANNELS_ID,
    "CHANNEL_CREATE": LOG_CHANNEL_CHANNELS_ID,
    # Role Add/Remove to Member
    "ROLE_ADD": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    "ROLE_REMOVE": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    "ROLE_UPDATE_MEMBER": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    # Kick/Ban
    "KICK": LOG_CHANNEL_MODERATION_ID,
    "BAN": LOG_CHANNEL_MODERATION_ID,
    "UNBAN": LOG_CHANNEL_MODERATION_ID,
    # Tickets - Uses Webhook (No Embed)
    "TICKET_CREATE": LOG_CHANNEL_TICKETS_ID,
    "TICKET_CLOSE": LOG_CHANNEL_TICKETS_ID,
    "TICKET_TRANSCRIPT": LOG_CHANNEL_TICKETS_ID,
    "TICKET_OPEN": LOG_CHANNEL_TICKETS_ID,
    "TICKET_DELETE": LOG_CHANNEL_TICKETS_ID,
    # Misc Member (Nickname/Username)
    "NICKNAME_UPDATE": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    "NICKNAME_CHANGE": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    "USER_UPDATE": LOG_CHANNEL_MEMBER_ROLE_CHANGES_ID,
    # Catch-all for related
    "APPEAL_SUBMITTED": LOG_CHANNEL_WARNINGS_ID,
    "APPEAL_APPROVED": LOG_CHANNEL_WARNINGS_ID,
    "APPEAL_DENIED": LOG_CHANNEL_WARNINGS_ID,
    "STAFF_POINT": LOG_CHANNEL_STAFF_POINTS_ID,
    "POINT_ADD": LOG_CHANNEL_STAFF_POINTS_ID,
    "POINT_REMOVE": LOG_CHANNEL_STAFF_POINTS_ID,
    # External/System Logs
    "EXTERNAL_LOG": LOG_CHANNEL_STAFF_POINTS_ID,
}
